export const services = [
  {
    slug: "reactive-repairs",
    name: "Reactive Repairs",
    short: "Diagnosis, attendance and completion with minimal disruption — coordinated across trades.",
    desc: "From urgent faults to unexpected building issues, our teams coordinate diagnosis, attendance and completion with minimal disruption to occupants and operations.",
    category: "Property Services",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&h=800&fit=crop",
    highlights: ["24/7 response", "Multi-trade capability", "Clear communication", "Completion documentation"],
  },
  {
    slug: "planned-maintenance",
    name: "Planned Maintenance",
    short: "Programmed works that keep portfolios safe, compliant and operational — without firefighting.",
    desc: "Scheduled maintenance programmes built around the way property teams actually work, with forward planning and transparent reporting.",
    category: "Property Services",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=800&fit=crop",
    highlights: ["PPM scheduling", "Asset lifecycle planning", "Portfolio reporting", "Minimal disruption"],
  },
  {
    slug: "electrical",
    name: "Electrical Services",
    short: "Inspection, testing, installation and remedial works by qualified engineers.",
    desc: "Complete electrical services from EICR and compliance to installations and reactive faults.",
    category: "Building Services",
    image: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=1200&h=800&fit=crop",
    highlights: ["EICR & testing", "Installations", "Emergency call-out", "Compliance certification"],
  },
  {
    slug: "hvac",
    name: "HVAC",
    short: "Heating, ventilation and climate systems kept efficient, compliant and reliable.",
    desc: "HVAC maintenance, repair and replacement across commercial and residential portfolios.",
    category: "Building Services",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1200&h=800&fit=crop",
    highlights: ["Planned servicing", "System diagnostics", "Energy efficiency", "Emergency repair"],
  },
  {
    slug: "plumbing",
    name: "Plumbing",
    short: "Responsive plumbing services for occupied properties and void works.",
    desc: "From leaks and blockages to full system upgrades, with clear communication to residents and managers.",
    category: "Building Services",
    image: "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=1200&h=800&fit=crop",
    highlights: ["Leak response", "Drainage", "Installations", "Void preparation"],
  },
  {
    slug: "gas",
    name: "Gas Services",
    short: "Gas Safe registered engineers for servicing, repairs and safety certification.",
    desc: "Gas servicing and safety checks carried out with rigorous documentation and resident coordination.",
    category: "Building Services",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=1200&h=800&fit=crop",
    highlights: ["Gas Safe registered", "CP12 certification", "Boiler servicing", "Emergency response"],
  },
  {
    slug: "fire-doors",
    name: "Fire Door Inspection & Maintenance",
    short: "Inspection, remediation and ongoing compliance for fire doors across portfolios.",
    desc: "Detailed inspections against regulatory standards, with remedial works and auditable documentation.",
    category: "Compliance & Safety",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=800&fit=crop",
    highlights: ["Regulatory inspections", "Remedial works", "Digital records", "Compliance reporting"],
  },
  {
    slug: "damp-mould",
    name: "Damp & Mould Remediation",
    short: "From diagnosis to prevention — technical remediation with resident care.",
    desc: "Root-cause investigation, remediation and preventive measures to protect occupants and building fabric.",
    category: "Compliance & Safety",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&h=800&fit=crop",
    highlights: ["Cause diagnosis", "Safe remediation", "Ventilation advice", "Prevention planning"],
  },
  {
    slug: "property-assessments",
    name: "Property Assessments",
    short: "Condition surveys and assessments that inform capital planning and compliance.",
    desc: "Comprehensive assessments providing clear, actionable reporting for maintenance and investment decisions.",
    category: "Property Services",
    image: "https://images.unsplash.com/photo-1560184611-6a68fd9edcb5?w=1200&h=800&fit=crop",
    highlights: ["Condition surveys", "Compliance audits", "Photo reporting", "Capital planning data"],
  },
  {
    slug: "refurbishment",
    name: "Refurbishment & Improvement Works",
    short: "Planned improvement works delivered with programme discipline and site control.",
    desc: "Refurbishment and improvement projects from kitchens and bathrooms to full building upgrades.",
    category: "Project Works",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&h=800&fit=crop",
    highlights: ["Programme management", "Multi-trade delivery", "Resident liaison", "Quality control"],
  },
];

export const sectors = [
  {
    slug: "property-management",
    name: "Property Management",
    headline: "Keeping managed portfolios operational without the coordination headache.",
    desc: "For managing agents balancing reactive calls, compliance and client expectations across dispersed portfolios.",
    services: ["Reactive Repairs", "Planned Maintenance", "Electrical", "Compliance Support"],
    considerations: "Tenant communication · Levy & service charge alignment · Out-of-hours coverage",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=800&fit=crop",
    challenges: ["High volume of reactive jobs", "Dispersed sites — JHB, Cape Town, Durban", "Tenant liaison at scale", "Audit-ready documentation"],
  },
  {
    slug: "social-housing",
    name: "Social Housing",
    headline: "Responsive, respectful and accountable service for residents and providers.",
    desc: "Designed for social housing institutions and public entities managing occupied homes with care and compliance at the core.",
    services: ["Damp & Mould", "Reactive Repairs", "Gas & Electrical", "Property Assessments"],
    considerations: "Resident vulnerability · Housing Code compliance · Damp & mould strategy",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&h=800&fit=crop",
    challenges: ["Damp & mould prevention", "Vulnerable residents", "Access & appointments", "Regulatory scrutiny"],
  },
  {
    slug: "commercial-property",
    name: "Commercial Property",
    headline: "Minimising downtime in spaces where every hour matters.",
    desc: "For landlords and facilities managers where disruption directly impacts productivity and revenue.",
    services: ["HVAC", "Electrical", "Plumbing", "Refurbishment"],
    considerations: "Business continuity · SLA-driven response · Out-of-hours working",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=800&fit=crop",
    challenges: ["Business continuity", "Out-of-hours access", "Multi-site SLAs", "Compliance across tenancies"],
  },
  {
    slug: "education",
    name: "Education",
    headline: "Safe, compliant estates that support learning — not interrupt it.",
    desc: "For schools, colleges and universities where safety checks and works must align with term times.",
    services: ["Compliance & Safety", "Planned Maintenance", "Electrical", "HVAC"],
    considerations: "Term-time planning · Safeguarding · Statutory compliance",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200&h=800&fit=crop",
    challenges: ["Term-time constraints", "Safeguarding", "Statutory compliance", "Budget certainty"],
  },
  {
    slug: "healthcare",
    name: "Healthcare",
    headline: "Building services that never compromise care.",
    desc: "For clinics, hospitals and care settings where environment directly affects wellbeing and compliance is non-negotiable.",
    services: ["HVAC", "Plumbing", "Gas", "Fire Doors"],
    considerations: "Infection control · Critical systems · Healthcare compliance",
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1200&h=800&fit=crop",
    challenges: ["Infection control", "Critical systems uptime", "Compliance evidence", "Minimal disruption"],
  },
  {
    slug: "hospitality",
    name: "Hospitality",
    headline: "Guest-ready properties, without the behind-the-scenes chaos.",
    desc: "For hotels, restaurants and leisure operators where presentation and reliability are commercial imperatives.",
    services: ["Plumbing", "Electrical", "HVAC", "Refurbishment"],
    considerations: "Guest experience · Peak-season readiness · Rapid response",
    image: "https://images.unsplash.com/photo-1551882547-b79c4176354d?w=1200&h=800&fit=crop",
    challenges: ["Guest disruption", "Peak periods", "Brand standards", "Rapid close-out"],
  },
];

export const projects = [
  {
    slug: "property-maintenance-programme",
    title: "Portfolio maintenance programme — illustrative scenario",
    sector: "Property Management",
    service: "Planned Maintenance",
    desc: "Scenario: a hypothetical residential portfolio in Gauteng and Western Cape — coordinating trades and reporting across dispersed sites.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=800&fit=crop",
    metrics: { properties: 125, weeks: 18, works: "1,400+", completion: "97%" },
    challenge: "Scenario — dispersed portfolio with inconsistent historic maintenance records, varied ages and access constraints across Johannesburg, Pretoria and Cape Town.",
    approach: "Illustrative approach: centralised programme planning with dedicated account management, phased access and weekly progress reporting.",
    outcome: "Illustrative outcome: programme completed on schedule with auditable documentation and forward maintenance plan — representative example.",
  },
  {
    slug: "hvac-replacement",
    title: "Commercial HVAC replacement — illustrative scenario",
    sector: "Commercial Property",
    service: "HVAC",
    desc: "Scenario: out-of-hours replacement of end-of-life systems in a hypothetical 4-storey office building in Sandton — illustrative approach to zero-downtime.",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1200&h=800&fit=crop",
    metrics: { properties: 1, weeks: 6, works: "4 floors", completion: "100%" },
    challenge: "Scenario — ageing system causing repeated failures during occupied hours; replacement needed without closing the building.",
    approach: "Illustrative approach: night and weekend installation with temporary climate control, phased commissioning and occupant briefings.",
    outcome: "Illustrative outcome: energy efficiency improvement and no unplanned climate downtime — representative scenario data.",
  },
  {
    slug: "damp-mould-response",
    title: "Social housing damp & mould response — illustrative scenario",
    sector: "Social Housing",
    service: "Damp & Mould",
    desc: "Scenario: hypothetical remediation across 86 homes in Durban and Gqeberha — diagnosis, remediation, ventilation and resident guidance.",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=1200&h=800&fit=crop",
    metrics: { properties: 86, weeks: 12, works: "200+ interventions", completion: "94%" },
    challenge: "Scenario — recurring damp reports with varied root causes; need for resident-sensitive, technically robust response.",
    approach: "Illustrative approach: moisture mapping, cause categorisation, safe remediation, ventilation upgrades and follow-up inspections.",
    outcome: "Illustrative outcome: repeat reports reduced; documentation supporting compliance reporting — illustrative scenario data.",
  },
  {
    slug: "electrical-compliance",
    title: "Multi-site electrical compliance — illustrative scenario",
    sector: "Education",
    service: "Electrical",
    desc: "Scenario: electrical testing and remedial works across 12 hypothetical education sites in Gauteng during holiday shutdown.",
    image: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=1200&h=800&fit=crop",
    metrics: { properties: 12, weeks: 3, works: "340+ remedials", completion: "100%" },
    challenge: "Scenario — large volume of testing and remedials within short holiday window with safeguarding constraints.",
    approach: "Illustrative approach: consolidated, police-cleared team deployment, school-by-school coordination and live defect tracking.",
    outcome: "Illustrative outcome: sites certified with remedial backlog cleared — representative example, illustrative data.",
  },
];

export const insights = [
  {
    slug: "cost-of-reactive-maintenance",
    title: "The real cost of reactive maintenance",
    category: "Operational Insight",
    date: "12 Mar 2026",
    read: "6 min",
    excerpt: "Why deferring planned works rarely saves money — and how portfolio teams quantify the true impact.",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop",
  },
  {
    slug: "planned-maintenance-reduces-disruption",
    title: "Why planned maintenance reduces disruption",
    category: "Maintenance Strategy",
    date: "28 Feb 2026",
    read: "5 min",
    excerpt: "Programming works around occupancy, not the other way around — a practical guide for facilities managers.",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop",
  },
  {
    slug: "choosing-maintenance-partner",
    title: "What property managers should look for in a maintenance partner",
    category: "Procurement",
    date: "19 Feb 2026",
    read: "7 min",
    excerpt: "Beyond price: the operational, technical and reporting capabilities that separate reliable partners from risk.",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop",
  },
  {
    slug: "damp-mould-prevention",
    title: "Damp and mould: moving from response to prevention",
    category: "Compliance",
    date: "04 Feb 2026",
    read: "8 min",
    excerpt: "How housing providers are shifting from case-by-case fixes to portfolio-wide damp and mould strategies.",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop",
  },
];
